//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateQuestion
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int CandidateUserId { get; set; }
        public bool IsDone { get; set; }
        public string Solution { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public Nullable<double> Ranked { get; set; }
        public string Review { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
