//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public string DateCreated { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string DateUpdated { get; set; }
        public string LastUpdateBy { get; set; }
        public string LastUpdateByDisplayName { get; set; }
    }
}
