//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSolutionQuestion
    {
        public int Id { get; set; }
        public int TestSolutionId { get; set; }
        public int QuestionId { get; set; }
        public string Solution { get; set; }
        public string Feedback { get; set; }
        public Nullable<double> Score { get; set; }
    
        public virtual TestSolution TestSolution { get; set; }
    }
}
